### ISSUE TITLE
Building from source fails due to weird subfolder names

### ISSUE THREAD

**Issue by VimalMollyn** [davidbailey00/notion-linux#21] opened 2020-12-22 10:02 UTC
Hi! First of all, thanks a lot for repackaging this app for Ubuntu! 

I was trying to build it from source and got the following error (shown in the picture).

![image](https://user-images.githubusercontent.com/62076354/102875621-0a99b600-446a-11eb-8d3e-05b15036f9fd.png)

On further debugging, I figured out that this was due to some odd subfolder names (they showed up as "??" in ls). After changing the folder names and rewriting the bash script, everything works fine. 

Any ideas on how to make it work with the default folder names?

**Comment by vtenfys** [comment] 2020-12-22 16:58
I haven't experienced this so I'm not sure what's going wrong. Can you tell me a bit about your system, e.g. are you using Ubuntu or a more obscure Linux distribution? Also, which parts of the Bash script did you change to get it working?

**Comment by VimalMollyn** [comment] 2020-12-23 12:52
I'm on Ubuntu 16.04. 

I renamed the subfolders of `notion-deb-builder/build/notion` to the following structure. 

![image](https://user-images.githubusercontent.com/62076354/102997568-7738b180-454b-11eb-8a52-d67e18d13d63.png)

Then I changed the bash script to point to these folders while extracting.

![image](https://user-images.githubusercontent.com/62076354/102997665-abac6d80-454b-11eb-8e43-05a5c2ea662a.png)

I also had to stop the extraction of the notion executable as that had the funky named folders.

**Comment by vtenfys** [comment] 2020-12-23 18:55
I believe this may be caused by an old version of 7zip - mine is version 16.02, while yours is version 9.20 which I can see is the latest in the Ubuntu 16.04 repositories. The extracted `.exe` folder structure is expected to look like this:

```
% tree build/notion     
build/notion
├── $PLUGINSDIR
│   ├── SpiderBanner.dll
│   ├── StdUtils.dll
│   ├── System.dll
│   ├── WinShell.dll
│   ├── app-64.7z
│   ├── nsExec.dll
│   ├── nsProcess.dll
│   └── nsis7z.dll
└── Uninstall\ Notion.exe

1 directory, 9 files
```

A newer version of `p7zip-full` is not available in the `xenial-backports` repository, however you could try manually [downloading and installing the deb from Ubuntu 20.04](https://packages.ubuntu.com/focal/amd64/p7zip-full/download) - let me know if that works!

**Comment by vtenfys** [comment] 2020-12-23 18:59
I have updated the README to reflect that p7zip version 9.20 does not seem to work with the script.

**Comment by VimalMollyn** [comment] 2020-12-24 20:09
> I believe this may be caused by an old version of 7zip - mine is version 16.02, while yours is version 9.20 which I can see is the latest in the Ubuntu 16.04 repositories. The extracted `.exe` folder structure is expected to look like this:
> 
> ```
> % tree build/notion     
> build/notion
> ├── $PLUGINSDIR
> │   ├── SpiderBanner.dll
> │   ├── StdUtils.dll
> │   ├── System.dll
> │   ├── WinShell.dll
> │   ├── app-64.7z
> │   ├── nsExec.dll
> │   ├── nsProcess.dll
> │   └── nsis7z.dll
> └── Uninstall\ Notion.exe
> 
> 1 directory, 9 files
> ```
> 
> A newer version of `p7zip-full` is not available in the `xenial-backports` repository, however you could try manually [downloading and installing the deb from Ubuntu 20.04](https://packages.ubuntu.com/focal/amd64/p7zip-full/download) - let me know if that works!

Sure! I'll try it out sometime this weekend. Thanks a ton!

**Comment by vtenfys** [comment] 2021-01-05 14:00
Closing as this is now documented in the readme; please let me know if this is still an issue with the latest p7zip

**Closed as completed by vtenfys** 2021-01-05 14:00 UTC
